# Generated by Django 5.1.4 on 2024-12-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created',
            new_name='created_at',
        ),
    ]
